import './style.css';
import type { GameFormat } from './format.js';
import { createF1Format } from './formats/f1/index.js';
import { createRaidFormat } from './formats/raid/index.js';
import { createFoundryFormat } from './formats/foundry/index.js';
import type { ServerMessage } from '../shared/protocol.js';
import { createEventSource } from './event-source.js';
const factories:Record<string,()=>GameFormat>={f1:createF1Format,raid:createRaidFormat,foundry:createFoundryFormat};
const requested=new URLSearchParams(location.search).get('game')??'f1';const format=(factories[requested]??createF1Format)();
let socket:WebSocket|null=null;let hydrated=false;
const focus=(terminalID:string)=>{if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'focus',terminalID}));};
const chrome=format.createChrome();const standings=format.createStandings(document.getElementById('standings')!,focus);const scene=format.createScene(document.getElementById('track') as HTMLCanvasElement,focus);
const source=createEventSource((events,reset,cursor)=>{format.onEvents(events,reset);format.onTimeline(cursor);hydrated=true;chrome.render();standings.render();scene.commit(performance.now());},()=>socket?.close());
function frame(now:number){if(hydrated)scene.frame(now);requestAnimationFrame(frame);}requestAnimationFrame(frame);
function connect(){socket=new WebSocket(`ws://${location.host}/ws`);socket.onmessage=e=>source.ingest(JSON.parse(e.data as string) as ServerMessage);socket.onclose=()=>setTimeout(connect,1000);}connect();
new ResizeObserver(()=>{scene.resize();if(hydrated)scene.frame(performance.now());}).observe(document.getElementById('track-wrap')!);
