import type { GameEvent } from '../../../shared/events.js';
import type { AgentStatus, ConnectionState } from '../../../shared/presentation.js';
import type { FinalResult, TeamColorToken } from '../../presentation.js';
import type { TimelineCursor } from '../../../shared/protocol.js';
import { stableHash } from '../../../shared/deterministic.js';
import { RaidRules, seededRaidAttackRate } from './rules.js';
import { raidClassStatsForUnit } from './roles.js';

export interface RaidGuildState { id:string; label:string; sourceOrder:number; stableOrder:number; colorToken:TeamColorToken }
export interface RaiderState { id:string; number:number; guildID:string; tabLabel:string; agentKind:string; status:AgentStatus; isFocused:boolean; sourceOrder:number; stableOrder:number; officialDamage:number; displayOrbit:number; attackRate:{multiplier:number;damageBand:number}; felled:boolean; queued:boolean; stunnedAtCamp:boolean; respawnUntil:number|null }
export interface RaidState { phase:'summoning'|'battle'|'bossDown'; stage:number; timelineTime:number; timelineRate:number; battleTime:number; bossDownElapsed:number; connection:ConnectionState; hasSnapshot:boolean; guilds:Map<string,RaidGuildState>; raiders:Map<string,RaiderState>; result:FinalResult|null }
export function initialRaidState():RaidState { return { phase:'summoning',stage:1,timelineTime:0,timelineRate:1,battleTime:0,bossDownElapsed:0,connection:{kind:'waiting'},hasSnapshot:false,guilds:new Map(),raiders:new Map(),result:null }; }
function free(preferred:number,max:number,used:Set<number>):number { for(let i=0;i<max;i++){const v=(preferred+i)%max;if(!used.has(v))return v;}throw new Error('identity space exhausted'); }
function teamGroups(s:RaidState){return [...s.guilds.values()].map(guild=>({guild,raiders:[...s.raiders.values()].filter(r=>r.guildID===guild.id)})).filter(g=>g.raiders.some(r=>!r.felled)).map(g=>({...g,damage:g.raiders.reduce((n,r)=>n+r.officialDamage,0)})).sort((a,b)=>Math.round(b.damage*1e6)-Math.round(a.damage*1e6)||a.guild.sourceOrder-b.guild.sourceOrder||a.guild.id.localeCompare(b.guild.id));}
function addGuild(s:RaidState,e:Extract<GameEvent,{kind:'team-joined'}>){if(s.guilds.has(e.team.id))return;const used=new Set([...s.guilds.values()].filter(g=>g.colorToken.kind==='palette').map(g=>g.colorToken.slot));const preferred=Number(stableHash(e.team.id)%12n);const palette=used.size<12;const slot=palette?free(preferred,12,used):[...s.guilds.values()].filter(g=>g.colorToken.kind==='pattern').length;s.guilds.set(e.team.id,{id:e.team.id,label:e.team.label,sourceOrder:e.team.sourceOrder,stableOrder:e.team.stableOrder,colorToken:{kind:palette?'palette':'pattern',slot}});}
function addRaider(s:RaidState,u:Extract<GameEvent,{kind:'unit-joined'}>['unit']){const old=s.raiders.get(u.id);if(old){Object.assign(old,{guildID:u.teamID,tabLabel:u.tabLabel,agentKind:u.agentKind,status:u.status,isFocused:u.isFocused,felled:false});return;}const used=new Set([...s.raiders.values()].map(r=>r.number-1));const number=free(Number(stableHash(u.id)%99n),99,used)+1;const active=[...s.raiders.values()].filter(r=>!r.felled&&!r.queued);const damage=s.phase==='battle'?Math.max(0,Math.min(...active.map(r=>r.officialDamage),RaidRules.newcomerDeficit)-RaidRules.newcomerDeficit):0;s.raiders.set(u.id,{id:u.id,number,guildID:u.teamID,tabLabel:u.tabLabel,agentKind:u.agentKind,status:u.status,isFocused:u.isFocused,sourceOrder:u.sourceOrder,stableOrder:u.stableOrder,officialDamage:damage,displayOrbit:damage,attackRate:{multiplier:1,damageBand:-1},felled:false,queued:s.phase==='bossDown',stunnedAtCamp:false,respawnUntil:null});}
function rate(s:RaidState,r:RaiderState){if(r.status==='done')return RaidRules.baseDamageRate*RaidRules.doneAttackFactor;const band=Math.min(Math.floor(r.officialDamage),57);if(r.attackRate.damageBand!==band)r.attackRate={damageBand:band,multiplier:seededRaidAttackRate(s.stage,r.id,band)};return RaidRules.baseDamageRate*r.attackRate.multiplier*raidClassStatsForUnit(r.number).damageRateMultiplier;}
function finishTime(s:RaidState,r:RaiderState){let v=r.officialDamage,t=0;if(r.status==='done')return(58-v)/(RaidRules.baseDamageRate*RaidRules.doneAttackFactor);const classMultiplier=raidClassStatsForUnit(r.number).damageRateMultiplier;while(v<58-1e-12){const band=Math.min(Math.floor(v),57);const speed=RaidRules.baseDamageRate*seededRaidAttackRate(s.stage,r.id,band)*classMultiplier;const end=Math.min(band+1,58);t+=(end-v)/speed;v=end;}return t;}
function move(s:RaidState,r:RaiderState,elapsed:number){let left=elapsed;while(left>1e-12&&r.officialDamage<58){const speed=rate(s,r);const end=Math.min(Math.floor(r.officialDamage)+1,58);const need=(end-r.officialDamage)/speed;const used=Math.min(left,need);r.officialDamage+=used*speed;r.displayOrbit+=used*speed;left-=used;if(need<=used+1e-9)r.officialDamage=end;}}
function down(s:RaidState){const groups=teamGroups(s);s.result={round:s.stage,top:groups.slice(0,3).map((g,i)=>({rank:i+1,teamID:g.guild.id,label:g.guild.label,colorToken:g.guild.colorToken,progress:g.damage}))};s.phase='bossDown';s.bossDownElapsed=0;}
function next(s:RaidState){s.stage++;s.phase='battle';s.battleTime=0;s.bossDownElapsed=0;s.result=null;for(const[id,r]of s.raiders){if(r.felled){s.raiders.delete(id);continue;}Object.assign(r,{officialDamage:0,displayOrbit:0,attackRate:{multiplier:1,damageBand:-1},queued:false,stunnedAtCamp:false,respawnUntil:null});}const parked=[...s.raiders.values()].filter(r=>r.status==='done'||r.status==='blocked').sort((a,b)=>a.stableOrder-b.stableOrder);parked.forEach((r,i)=>r.displayOrbit=(i+1)/(parked.length+1));}
export function advanceRaidTo(s:RaidState,target:number):RaidState{if(target<s.timelineTime-1e-9)throw new RangeError('timeline cannot move backwards');let left=target-s.timelineTime;while(left>1e-12){if(s.phase==='summoning')break;if(s.phase==='bossDown'){const used=Math.min(left,8-s.bossDownElapsed);for(const r of s.raiders.values())if(!r.felled&&!r.queued&&(r.status==='working'||r.status==='done'))r.displayOrbit+=used*RaidRules.baseDamageRate*RaidRules.victoryOrbitFactor;s.bossDownElapsed+=used;s.battleTime+=used;left-=used;if(s.bossDownElapsed>=8-1e-9)next(s);else break;continue;}const attackers=[...s.raiders.values()].filter(r=>(r.status==='working'||r.status==='done')&&!r.felled&&!r.queued);const until=attackers.length?Math.min(...attackers.map(r=>finishTime(s,r))):Infinity;const used=Math.min(left,until);for(const r of attackers)move(s,r,used);s.battleTime+=used;left-=used;if(until<=used+1e-9)down(s);else break;}s.timelineTime=target;return s;}
export function setRaidCursor(s:RaidState,c:TimelineCursor){advanceRaidTo(s,c.timelineTime);s.timelineRate=c.timelineRate;return s;}
export function foldRaid(s:RaidState,e:GameEvent):RaidState{advanceRaidTo(s,e.at);switch(e.kind){case'connection-changed':s.connection=e.connection;break;case'team-joined':addGuild(s,e);break;case'team-updated':{const g=s.guilds.get(e.teamID);if(g)g.label=e.label;break;}case'unit-joined':addRaider(s,e.unit);break;case'unit-profile-changed':{const r=s.raiders.get(e.unitID);if(r)Object.assign(r,{guildID:e.profile.teamID,tabLabel:e.profile.tabLabel,agentKind:e.profile.agentKind,isFocused:e.profile.isFocused});break;}case'status-changed':{const r=s.raiders.get(e.unitID);if(r){r.stunnedAtCamp=e.to==='blocked'&&(r.status==='idle'||r.queued);if(e.to!=='blocked')r.stunnedAtCamp=false;r.status=e.to;}break;}case'unit-session-restarted':{const r=s.raiders.get(e.unitID);if(r)r.respawnUntil=s.battleTime+4;break;}case'unit-departed':{const r=s.raiders.get(e.unitID);if(r)r.felled=true;break;}case'snapshot-applied':if(!s.hasSnapshot){s.hasSnapshot=true;s.phase='battle';s.stage=0;next(s);}break;}return s;}
export function replayRaid(events:readonly GameEvent[]){const s=initialRaidState();for(const e of events)foldRaid(s,e);return s;}
