import type { EntryPlacement, EntryPresentation, GameOverlay, FormatViewBase, TeamStanding } from '../../presentation.js';
import { RaidRules } from './rules.js';
import { raidClassStatsForUnit } from './roles.js';
import type { RaiderState, RaidState } from './fold.js';
export interface RaidView extends FormatViewBase { stage:number; leaderDamage:number; bossHpFraction:number }
function place(r:RaiderState):EntryPlacement{const p=r.displayOrbit-Math.floor(r.displayOrbit);if(r.queued)return{kind:'queued'};if(r.felled)return{kind:'departed'};if(r.status==='working')return{kind:'active',progress:p};if(r.status==='idle')return{kind:'resting'};if(r.status==='done')return{kind:'coolingDown',progress:p};return r.stunnedAtCamp?{kind:'blockedResting'}:{kind:'blockedActive',progress:p};}
function overlay(s:RaidState):GameOverlay{if(s.connection.kind==='protocolError')return{kind:'suspended',detail:s.connection.detail};if(!s.hasSnapshot)return{kind:'connecting'};if(s.connection.kind!=='live')return{kind:'frozen'};if([...s.raiders.values()].every(r=>r.felled))return{kind:'noUnits'};return{kind:'none'};}
function display(s:RaidState,r:RaiderState){if(s.connection.kind!=='live'||r.felled||r.queued)return 0;if(s.phase==='bossDown')return(r.status==='working'||r.status==='done')?RaidRules.baseDamageRate*RaidRules.victoryOrbitFactor*s.timelineRate:0;if(r.status==='working')return RaidRules.baseDamageRate*(r.attackRate.damageBand<0?1:r.attackRate.multiplier)*raidClassStatsForUnit(r.number).damageRateMultiplier*s.timelineRate;if(r.status==='done')return RaidRules.baseDamageRate*RaidRules.doneAttackFactor*s.timelineRate;return 0;}
export function projectRaid(s:RaidState):RaidView{const q=(v:number)=>Math.round(v*1e9)/1e9;const groups=[...s.guilds.values()].map(guild=>({guild,raiders:[...s.raiders.values()].filter(r=>r.guildID===guild.id)})).filter(g=>g.raiders.some(r=>!r.felled)).map(g=>({...g,damage:q(g.raiders.reduce((n,r)=>n+r.officialDamage,0))})).sort((a,b)=>Math.round(b.damage*1e6)-Math.round(a.damage*1e6)||a.guild.sourceOrder-b.guild.sourceOrder||a.guild.id.localeCompare(b.guild.id));const teams:TeamStanding[]=groups.map((g,i)=>({id:g.guild.id,rank:i+1,label:g.guild.label,colorToken:g.guild.colorToken,progress:g.damage,entries:g.raiders.slice().sort((a,b)=>Math.round(b.officialDamage*1e6)-Math.round(a.officialDamage*1e6)||a.number-b.number||a.id.localeCompare(b.id)).map((r):EntryPresentation=>({id:r.id,unitNumber:r.number,teamID:r.guildID,workspaceLabel:g.guild.label,tabLabel:r.tabLabel,agentKind:r.agentKind,status:r.status,colorToken:g.guild.colorToken,officialProgress:q(r.officialDamage),placement:place({...r,displayOrbit:q(r.displayOrbit)}),displaySpeed:display(s,r),isFocused:r.isFocused,isDeparted:r.felled,isQueued:r.queued,showsNewStint:r.respawnUntil!==null&&s.battleTime<r.respawnUntil}))}));const leader=q(Math.max(0,...[...s.raiders.values()].filter(r=>!r.queued).map(r=>r.officialDamage)));return{phase:s.phase==='summoning'?'awaitingUnits':s.phase==='battle'?'live':'results',round:s.stage,stage:s.stage,leaderProgress:leader,leaderDamage:leader,bossHpFraction:q(Math.max(0,1-leader/RaidRules.bossHealth)),teams,results:s.result,connection:s.connection,overlay:overlay(s)};}
